language: cpp
compiler:
  - clang
cache: apt
install: true
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y portaudio19-dev libopenal-dev libva-dev
script:
  - ./tools/ci/travis_build.sh
notifications:
  irc:
    channels:
      - "chat.freenode.net#qtav"
  email:
    recipients:
      - wbsecg1@gmail.com
    on_success: change
    on_failure: always
env:
  - LANG="en_US.UTF-8"
os:
  - linux
