dist: trusty
#TODO: mingw cross build
language: cpp
cache: apt

matrix:
  include:
    - os: osx
      compiler: clang
      env:
      - QT=brew
      - AV=ffmpeg-brew
    - os: linux
      compiler: gcc
      env:
      - QT=4.8.6
      - AV=ffmpeg-1.0.10
      - CC=gcc
    - os: linux
      compiler: clang
      env:
      - QT=5.0.2
      - AV=ffmpeg-1.2.10
    - os: linux
      compiler: clang
      env:
      - QT=5.1.1
      - AV=ffmpeg-2.0.6
    - os: linux
      compiler: clang
      env:
      - QT=5.2.1
      - AV=ffmpeg-2.2.11

branches:
  only:
    - master
    - prelease
    - ci/travis
    - /^travis.*$/
    - dev

git:
  submodules: true

install: . tools/ci/$TRAVIS_OS_NAME/install.sh

script:
  - ./tools/ci/$TRAVIS_OS_NAME/script.sh

after_success: ./tools/ci/$TRAVIS_OS_NAME/after_success.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net#qtav"
  email:
    recipients:
      - wbsecg1@gmail.com
    on_success: change
    on_failure: always
