branches:
  only:
    - master
    - prelease
    - ci/appveyor
    - appveyor

environment:

  matrix:
  - arch: x64
    cc: VS2013
    qt: 5.5.0
    suffix: -debug
    mode: debug
    QTDIR: C:\Qt\5.5\msvc2013_64

  - arch: x86
    cc: VS2013
    qt: 5.5.0
    suffix: -xp
    mode: release
    QTDIR: C:\projects\QtAV\build\Qt

  - arch: 32
    cc: MinGW
    qt: 5.5.0
    suffix: GCC492-dwarf
    mode: release
    QTDIR: C:\Qt\5.5\mingw492_32

matrix:
  fast_finish: false

init:
  - set vcarch=%arch%
  - if "%arch%" == "x64" set vcarch=amd64
  - if not %cc%==MinGW call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" %vcarch%
  - C:\Qt\Tools\mingw492_32\bin\g++ --version
  - echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
  - echo PROCESSOR_IDENTIFIER=%PROCESSOR_IDENTIFIER%
  - echo QTDIR=%QTDIR%

install:
  - git submodule update --init
  - mkdir build
  - cd build
  - ..\tools\ci\win\install_dep.bat

before_build:
  - set PATH=%QTDIR%\bin;%PATH%
  - if %cc%==MinGW set PATH=C:\Qt\Tools\mingw492_32\bin;%PATH%
  - echo PATH=%PATH%

build_script:
  - ..\tools\ci\win\build.bat

after_build:
  - ..\tools\ci\win\deploy_win.bat

test: off

artifacts:
  - path: 'QtAV*.7z'  # relative to repo root

deploy:
  provider: FTP
  protocol: sftp
  host: frs.sourceforge.net
  username: novesky,qtav
  password:
    secure: 2mQg4oxdX8S7rMJz2TCGGg==
  folder: /home/frs/project/q/qt/qtav/ci # why always relative path even if starts with / ? I have to make a link home/frs/project/q/qt/qtav/ci => /home/frs/project/q/qt/qtav/ci
  active_mode: false
